# Generated by Django 5.2.7 on 2025-12-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_commentmodel_author_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_entered_form', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
