# Generated by Django 5.2.7 on 2026-01-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ordermodel_email_ordermodel_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_entered_form',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='wish',
        ),
        migrations.CreateModel(
            name='PhotosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='orders/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ordermodel')),
            ],
        ),
    ]
