# Generated by Django 5.2.7 on 2026-01-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_ordermodel_ispayload_ordermodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(default='+380', null=True),
        ),
    ]
