# Generated by Django 5.2.7 on 2025-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='name_and_city',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='author_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
