# Generated by Django 5.2.7 on 2025-12-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_commentmodel_author_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='author_city',
            field=models.CharField(blank=True, default='Не вказано', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='author_name',
            field=models.CharField(blank=True, default='Анонім', max_length=100, null=True),
        ),
    ]
