# Generated by Django 5.2.7 on 2025-12-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='wish',
            field=models.TextField(null=True),
        ),
    ]
