# Generated by Django 5.2.7 on 2026-01-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_ordermodel_is_entered_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='wish',
            field=models.TextField(null=True),
        ),
    ]
