# Generated by Django 5.2.7 on 2026-01-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ordermodel_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='isPayload',
            field=models.BooleanField(default=False),
        ),
    ]
