# Generated by Django 5.2.7 on 2026-01-20 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_ordermodel_ispayload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='isPayload',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Draft', 'Чернетка'), ('Waiting_payment', 'Очікування оплати'), ('Paid', 'Сплачено'), ('Canceled', 'Скасовано')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
