# Generated by Django 5.2.7 on 2026-01-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_ordermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='mono_invoice_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
